LIME-405 - Increases SQS retention from 4 days to 7 days
alphagov/di-ipv-cri-common-infrastructure pull request #55
Opened 2023-01-17 15:21 UTC by MMcC-GDS

## Proposed changes

### Issue tracking

- [LIME-405](https://govukverify.atlassian.net/browse/LIME-405)

2023-01-18 16:09 UTC, merlinc requested changes

2023-01-18 16:09 UTC, merlinc commented on txma/template.yaml
> +    Default: 345600 # 4 days
Numbers like this are really difficult to eyeball and know that they are correct.

Could we implement something like https://github.com/alphagov/di-ipv-cri-kbv-api/blob/main/infrastructure/lambda/template.yaml#L147-L162 in order to capture the number and units separately?

2023-01-18 16:09 UTC, merlinc commented on .github/workflows/post-merge-publish-txma-infrastructure.yaml
> +        target: [ FRAUD_DEV ]
Why are we removing all of these other environments?

2023-01-20 11:23 UTC, gds-jbentham commented on .github/workflows/post-merge-publish-txma-infrastructure.yaml
> +        target: [ FRAUD_DEV ]
Only so we can check it doesnt cause any issues before pushing to all the CRIs

2023-01-20 11:23 UTC, MMcC-GDS commented on .github/workflows/post-merge-publish-txma-infrastructure.yaml
> +        target: [ FRAUD_DEV ]
At the moment, it is purely for testing purposes. This change is to be reverted.

2023-01-20 11:26 UTC, gds-jbentham commented on txma/template.yaml
> +    Default: 345600 # 4 days
In that case we read the unit and the value in our code this time its an AWS config value so were limited to adhering to their formats

2023-01-20 11:37 UTC, mrdoodles commented on .github/workflows/post-merge-publish-txma-infrastructure.yaml
> +        target: [ FRAUD_DEV ]
I think this is good just to test this in Fraud but it needs to be updated again to include the other environments once proven

2023-01-20 11:47 UTC, mrdoodles approved these changes

2023-01-20 14:48 UTC, gds-jbentham approved these changes

2023-01-20 14:48 UTC, merged